@startuml
actor Utilisateur as User
top to bottom direction
usecase (Modérer Membre) as create
:User: -right- create
(Se loguer) ..> create : << extends >> 
note top of  (Se loguer) : "Si pas encore logué"
(Vérifier Droit Administration) <.. create : <<include >>
(Sélectionner Groupe) <.. create : <<include >>
(Sélectionner Membre) <.. create : << include >>
(Choisir Action Modération) <.. create : <<include >>
(Notifier Groupe) <.. create : << include >>
(Notifier Membre) <.. create : << include >>
(Suspendre Temporairement) ..> create : << extends >>
(Bannir Définitivement) ..> create : << extends >>
(Rétablir Droit) ..> create : << extends >>
(Demander Confirmation Action) ..> create : << extends >>
@enduml


