@startuml
title Quitter Groupe

actor Utilisateur as User

(Se loguer) <.. (Quitter Groupe) : extends 

note top of  (Se loguer) : "Si pas encore logué"

(User) .> (Quitter Groupe)

(Renseigner Groupe) ..> (Quitter Groupe) : include
(Verifier \n appartenance)..>(Quitter Groupe) : include
(Confirmer \n action) ..> (Quitter Groupe) : include
(Supprimer utilisateur \n du groupe) <.. (Quitter Groupe) : extends
note top of  (Supprimer utilisateur \n du groupe) : "Si tout les includes sont valides"
(Notifier \n membres du groupe) <.. (Quitter Groupe) : extends
(Libérer ressources) <.. (Quitter Groupe) : extends
@enduml