@startuml

actor Utilisateur as User

(Se loguer) ..> (Lire Message Groupe) :  << extends >>

note top of  (Se loguer) : "Si pas encore logué"

(User) .> (Lire Message Groupe)
(Renseigner Groupe) <.. (Lire Message Groupe) : << include >>
(Verifier \n Groupe) <.. (Lire Message Groupe) : << include >>
(Verifier \n appartenance)<.. (Lire Message Groupe) : << include >>
(Afficher \n messages) ..> (Lire Message Groupe) : << extends >>
note top of  (Afficher \n messages) : "Si tout les includes sont validés"
(Libérer ressources) ..> (Lire Message Groupe) : << extends >>
@enduml