@startuml
title Lister Groupe
actor Utilisateur as User 

(Se loguer) <.. (Lister Groupe) : << extends >> 

note top of  (Se loguer) : "Si pas encore logué"

(User) .> (Lister Groupe) 

(Charger données \n groupes) <.. (Lister Groupe)  : include
(Afficher liste groupes) <.. (Lister Groupe) : include
(Afficher nom groupe) <.. (Lister Groupe) : include
(Trier liste groupes) <.. (Lister Groupe) : extend

@enduml