@startuml
title Lister Groupe
actor Utilisateur as User 

(Se loguer) ..> (Lister Groupe) : << extends >>

note top of  (Se loguer) : "Si pas encore logué"

(User) .> (Lister Groupe) 

(Charger données \n groupes) <.. (Lister Groupe)  : << include >>
(Afficher groupes existant) ..> (Lister Groupe) : << extends >>
note top of  (Afficher groupes existant) : "Si tout les includes sont valides"

@enduml