@startuml
actor Utilisateur as User
top to bottom direction
usecase (Supprimer groupe) as create
:User: -right- create
(Se loguer) <.. create : << extends >> 
note top of  (Se loguer) : "Si pas encore logué"
(Vérifier Droit Gestionnaire) ..> create : <<include >>
(Vérifier Groupe) ..> create : << include >>
(Notifier Groupe) ..> create : << include >>
(Supprimer Groupe) <.. create : << include >>
(Libérer Ressources) <.. create : << include >>
(Confirmer Suppresion) <.. create : << extends >>
(Archiver Stats) <.. create : << extends >>

@enduml


