
@startuml
actor Utilisateur as User
top to bottom direction
usecase (Fusionner groupe) as create
:User: -right- create

(Se loguer) ..> create : << extends >> 

note top of  (Se loguer) : "Si pas encore logué"

(Renseigner premier Groupe) ..> create : << include >>
(Vérifier Group 1) ..> create : << include >>
(Renseigner deuxième Groupe) ..> create : << include >>
(Vérifier Groupe 2) ..> create : << include >>
(Deplacer membre du groupe 1 dans groupe 2) <.. create : << extends >>
note top of  (Deplacer membre du groupe 1 dans groupe 2) : "Si les deux groupes sont valides"
(Supprimer groupe 2) <.. create : << extends >>
note top of  (Supprimer groupe 2) : "Si les deux groupes sont valides"
(Notifier membres des groupes) <.. create : << extends >>

@enduml
